// create an array to use with modal like in GOT execise
const sharkType = [
    {
        img: "SharkImages/whaleshark2.jgp",
        bio: "The Whale Shark(Rhincodon typus)Also known as a ’gentle giant’, is the largest known fish species in the world and have a life span of about 70 years. The average size of a Whale Shark is 40ft long and weighs in at an astonishing 15 tons(30,000 lbs). It is slow-moving, filter feeding shark. The Whale Shark has a mouth that opens up to 1.5m wide and has over 300 rows of tiny teeth and 20 filter pads to help it catch its prey. Whale Sharks are usually found in tropical and warm open seas. Whale Sharks can give birth up to 300 pups but not all at once. Evidence suggests that female Whale Sharks retain sperm from mating and give birth to young over a prolonged period of time. Whale Sharks are docile and not a threat or danger to humans. Many reports indicate that Whale Sharks will play with divers and allows swimmers to catch a ride on their dorsal fins. Due to increasing overfishing and illegal poaching of its fins and liver, the Whale Shark is an endangered species. "    
    },
    {
        img: "SharkImages/great-white-shark.jpg",
        bio: "The Great White Shark(Carcharodon carcharias) Is the largest predatory fish in the world and can live up to 70 years. Great Whites can grow over 20 ft and weigh in over 2.5 tons (5,000lbs), with the females being bigger than the males. Great Whites like many sharks have sensitive snouts which house a sensory organ called Ampullae of Lorenzini that can detect tiny electromagnetic fields generated by animals. The Great Whites’ organ is so sensitive that it can detect half a billionth of a volt and at close range can sense an animals’ heartbeat. Great White sharks are very adaptive and having many techniques to increase the success of their hunts. Some on these techniques include ‘spy-hopping’, where they lift their heads above the sea surface to look at objects or prey. There is also their most famous hunting technique called ‘breaching’ in which they propel themselves toward their prey at high speeds launching them out of the water. This hunting technique is only observed at Seal Island in False Bay, South Africa. Great White Sharks have no known predators besides rare encounters with Orcas and human carelessness. Great White sharks are not endangered yet, but are in a Vulnerable status due to overfishing. Contrary to popular belief Great White Sharks are not mindless killing machines that hunt indiscriminately. Out of the 100-plus shark attacks that happen every year less than a third are caused by Great Whites and most if all are non-fatal. Most attacks are due to the sharks curiosity and need to identify objects  with their mouths through a process called ‘sample biting’. So if a shark bites you, they are just curious about you and want to give you kisses."
    },
    {
        img: "SharkImages/hammerhead1.jpg",
        bio: "The Great Hammerhead Shark(Sphyrnidae mokarran) are apex predators that are found in coastal, warm waters world wide. Hammerhead sharks can grow up to 20 feet in length and weigh up 1,000lbs. Great Hammerheads conserve energy and reduce drag by swimming on their side. They use their dorsal fins to create lift and spend almost 90% of their time swimming this way. This swimming technique is called ‘Rolled Swimming’. They are solitary and aggressive hunters who feed primarily on prey on the sea floor. Their heads are filled with electrical receptors that can even detect prey hiding in the sand. Their wide-set eyes gives them an almost 360 degree view of their surroundings. They have been known to pin down their prey with their massive heads while taking bites out of them to cripple them. Their odd shaped heads are perfect for hunting stingrays. They do not hunt prey bigger than stingrays and will attack humans when provoked. Great Hammerhead sharks are listed as an endangered species due to their slow reproduction rate and high bycatch mortality and shark fin harvesting."
    },
    {
        img: "SharkImages/tigershark3.jpg",
        bio: "The Tiger Shark(Galeocerdo cuvier) can grow up to 25 feet and weigh in at a ton(2,000lbs), with the females growing bigger than the males. Tiger sharks are named for their dark vertical stripes found on adolescents. As these sharks mature their stripes start to fade and almost disappear. Tiger sharks are ferocious nocturnal  predators and can survive weeks without food. Famously known as the oceans garbage disposal, these sharks have been known to eat almost anything they can set their teeth in. They are consummate scavengers, with excellent sense of sight and smell. They have sharp serrated teeth and powerful jaws capable of crushing the shells of sea turtles. The stomach contents of captured Tiger sharks have been said to contain all kinds of prey and even license plates and old tires. When Tiger sharks close in on their prey, they tend to move slowly and silently, just like tigers stalking prey. This slow movement or ‘stealth mode’ together with their natural camouflage prevents the Tiger shark from being detected until it’s too late for their prey to escape. They are found in tropical and subtropical waters. Tiger sharks have very few predators. They are only prey to Orcas and Great White Sharks. They also fall prey to human fisheries both accidental and targeted. Tigers like most other sharks are victims to shark finning, overfishing and population control efforts by culling them for tourism destinations putting them in the ’near threatened’ status. Like most sharks they also have a slow reproduction rate and take years to mature."
    },
    {
        img: "SharkImages/threshershark2.jpg",
        bio: "The Thresher Shark(Alopias vulpinus) can grow up to 20 feet and weigh in at almost 1,100lbs. Threshers are most famously known for their long scythe like tails that measure half of their total length. One of the most impressive traits of Threshers is that they use their long tails to catch their prey by tricking and luring prey, once close enough they whip and stun their prey with their tails. Once their prey is disabled or crippled they attack their prey with speed assaults taking bites on each attack until they completely eat the entire prey. They generally feed on small prey such as fish crustaceans and sometimes small birds due to their small mouths. Threshers are very agile and been known to make quick turns like dolphins and are one of the only sharks to jump fully out of the water(breaching). They are strong swimmers and reach a top speed of 30mph. Threshers average life span is 20 years. Thresher sharks prefer the open waters when they mature and are mostly found 500m below the surface. Thresher sharks are not a threat to humans and generally swim away when they see a human. The only recorded attack was the individuals fault for provoking the shark. Humans are more of a threat to this beautiful species due to the fact that they are hunted for their unique tails. Thresher sharks are highly vulnerable and listed as a vulnerable to extinction status by the World Conservation Union."
    },
    {
        img: "SharkImages/bullshark1.jpg",
        bio: "The Bull Shark(Carcharhinus leucas) grow up to 13 feet and weigh in at about 700lbs and have a life span over 25 years. Contrary to popular belief, Bull sharks are more dangerous and aggressive than Great White sharks. Their testosterone to body size levels is far greater than that of a Great White, which makes them extremely dangerous to humans especially since they’ve been known to swim in fresh waters. Bull sharks are one of the only sharks to swim up fresh water and even stay in rivers and lakes. They are able to survive in fresh water because they have special glands and kidney functions that help them retain salt. A very versatile and adaptable animal the Bull shark is an aggressive opportunistic hunter targeting anything it can sink its teeth into. While Their habitats vary, Bull sharks prefer shallow coastal, murky waters where visibility is low in order to ambush unsuspecting prey. There is evidence that they swim up rivers to breed and use them as nurseries until they mature. Although Bull sharks have very few predators they use nurseries to shield them and protect them from larger predators. Bull sharks, just like most sharks are vulnerable to overfishing and targeting for their fins and livers. Most nurseries are in danger of being overfished and there has been a steady decline in size and population." 
    },
    {
        img: "SharkImages/sfmako3.jpg",
        bio: "The Short Finned Mako Shark(Isurus oxyrinchus) reaching top speeds over 45mph, the Short Finned Mako is the fastest shark and one of the fastest fish in the world. These Makos can grow past 12 feet and weigh at least 1,200 lbs, despite its size and weight, they are incredibly athletic and agile. They are also one of the few sharks in the world that are able to jump straight out of the water at incredible heights when hunting. They are migratory and travel long distances for food and mating. Makos’ habitat ranges from almost anywhere in the world. These Makos are set apart from most sharks due to their beautiful characteristics and range of colors. They are aggressive hunters and will attack humans in defense when provoked. Some of these attacks have been fatal due to the overwhelming power and speed of these predators, but just like most sharks they are not interested in humans and tend to avoid them. Most attacks on humans happen when they are captured and unfortunately pregnant Makos will abort their pups if captured, causing loss of life and research opportunities. Due to the rapid depletion of the Mako population caused by commercial, recreational and accidental fishing they are an endangered species."
    },
    {
        img: "SharkImages/blueshark3.jpg",
        bio: "The Blue Shark(Prionace glauca) can grow up to 13 feet and weigh a max weight of 450lbs. They have a sleek, slender tapered body made for agile and graceful movements in the water. They can be easily mistaken for shark pups which can make them dangerous to humans. They have distinct blue and dark blue colors which allows them to easily blend into the open waters. Blue sharks prefer deep cool waters and travel all over the seas except artic waters. Blue sharks will swim thousands of miles in a very short period of time for food or mating. An intresting fact about Blue sharks is that they will eat until they are ready to burst and sometimes throw up their food from overeating. Blue sharks will eat almost anything they can. They are also one of the few sharks that live and migrate with ‘schools’(large group made up of other sharks). They also have a hierarchy within these schools and are seperated by size and sex. Despite their speed and agility, Blue sharks fall prey to bigger sharks and human fishing practices. Humans hunt these sharks for their beautiful skin and other body parts, putting them in the Near Threatened status."
    },
    {
        img: "SharkImages/owtshark3.jpg",
        bio: "The Oceanic White Tip Shark(Carcharhinus longimanus) can grow up to 13 ft and weigh a max of 370lbs. White Tips have a life span of about 20 years and mature after 6-7 years. Oceanic White  Tips are one of the most widely ranging sharks and have a habitat that expands most of the world. White Tips live out in the open ocean and one of the only shark species that does not stop moving because they lack the ability to pump water across their gills. They must constantly keep swimming with their mouths slightly opened in order to have enough oxygen. They have been referred to the ‘dogs of the sea’ scene they exhibit dog like behavior when attacking and following ships. It has been rumored that these sharks are responsible for more human attacks and fatalities than any other shark combined. This is because they are the first to appear during ship wrecks or downed aircraft. Despite this these sharks are widely targeted for their unique fins. Their numbers have declined over 70% since 1992. They are in a vulnerable status near endangered because they are victims of overfishing and shark finning practices."
    },
    {
        img: "SharkImages/Basking shark1.jpg",
        bio: "The Basking Shark(Cetorhinus maximus) is the second largest fish in the ocean with a maximum size of up to 32 feet and weigh in at over 13,000lbs with a life span of about 50 years. The Basking shark is one of three filter feeding sharks in the world. Unlike the Whale shark that sucks in water through various muscles in its mouth, the Basking shark swims with its mouth wide open catching plankton and small organisms. It then closes its mouth pushing the water through its gills and trapping its prey inside. It has been known to filter 1,500-2,000 cubic meters of water per hour to obtain enough food. Their habitat is all over the world but they prefer sub-polar waters. It’s habitat changes depending on its food that it hunts. Basking sharks are slow moving and docile. They are non-threatening to humans and will allow swimmers to get close enough to catch a ride. Despite its huge mouth it can not swallow humans or large prey. This rare shark has little information on it due to its elusiveness and lack of scientific research. They are targeted like most sharks for its fins, liver, meat and cartilage and in a vulnerable status. For over 20 years their populations have drastically declined and even though conservation acts are in place they have not yet recovered like most sharks due to their slow growth and reproduction rate."
    },
    {
        img: "SharkImages/greenland-shark2.jpg",
        bio: "The Greenland Shark(Somniosus microcephalus) have been known to grow up to 21 ft and weigh in as much as 2,100lbs, they are on of the largest sharks in the world and also oldest. Greenland sharks have a life span longer than any other species, at a max of 512 years with the average being 390 years. This elusive shark is very rare and there is very little research done on it. What is know is that they swim very slowly at about less than 1mph, because of this they have been dubbed ‘sleeper sharks’. Another crazy fact about this shark is that they are blind because of parasites called copepods attaching to their corneas. They use their impeccable sense of smell to locate food. Greenland sharks are scavengers and will eat anything they can find. Fortunately these sharks are not widely targeted since they have very small fins and their meat is poisonous when fresh and need to be prepared a certain way in order to be consumed. They are still victims of accidental bycatch and since their numbers are unknown they are classified as near threatened."
    },
    {
        img: "SharkImages/goblin-shark2.jpg",
        bio: "The Goblin Shark(Mitsukurina owstoni) like something out of horror movie the Goblin shark is one of the most fascinating species to have ever lived. Having a lineage of over 125 million years old, this pink skinned shark has a distinct profile. Growing up to 13ft long and weigh in at 460lbs, they have a distinctive flat and elongated snout(looks like a blade) that grows above its eyes and past highly protrusible jaw. The Goblin shark has a flabby body and small fins making it slow and sluggish. This shark is a deep sea animal and prefers to stay at depths off over 3,150 ft and go past 4,500 ft deep. They hunt on the seafloor and will sometimes come up to the surface at night. Their huge snout contains sensitive sensory organs that allow it to detect electromagnetic pulses from potential prey. Typically an ambush predator due to its slow movement, very little is know about this crazy looking shark. These sharks have not been able to survive in aquariums due to the fact that they live in highly pressurized depths. They are not targeted by fisheries since they live deep in the ocean floor and are rarely caught accidentally."
    }
]


// get buttons for all sharks into a node list
let sharkList = document.querySelector(".shark-list");
console.log(sharkList);
let sharks = document.querySelectorAll(".sharks");
console.log(sharks);
// get the shark modal element
let sharkModal = document.querySelector(".sharkModal");
// get the shark content element
let sharkContent = document.querySelector(".sharkContent");
// create new image element
let sharkImg = document.querySelector("img")
// create new paraTag element
let sharkPara = document.createElement("p");
// get the close button
let closeModal = document.querySelector(".closeModal");

// add eventlistener on sharks to open sharkModal 
for(let i = 0; i < sharks.length; i++) {
    sharks[i].addEventListener("click", function() {    
        //console.log("baby shark");
        sharkModal.style.display = "block";
        sharkImg.src = sharkType[i].img
        sharkPara.innerHTML= sharkType[i].bio
        sharkContent.appendChild(sharkPara)
    })
}

// add eventlistener to close sharkModal with close button
closeModal.addEventListener("click", function() {    
    sharkModal.style.display = "none";
})
// add eventlistener to close modal when clicked outside of window
window.addEventListener("click", function(e) {
    if(e.target == sharkModal){
        sharkModal.style.display = "none";
    }
})